import AppKit
import AVFoundation

/// Every sound Zera makes. The files live in `Resources/Sounds` and are generated by
/// `scripts/synth_sounds.py`; all of them come from one pentatonic scale, so overlaps stay in tune.
enum ZeraSound: String, CaseIterable {
    // Zera
    case tap = "zera_tap", huff = "zera_huff", hello = "zera_hello", wake = "zera_wake"
    case lift = "zera_lift", land = "zera_land", caption = "caption_pop"
    // Island
    case islandOpen = "island_open", islandClose = "island_close", tab = "tab_switch", button = "button_press"
    // Files and the shelf
    case fileHover = "file_hover", fileCatch = "file_catch", fileReject = "file_reject"
    case fileDragOut = "file_drag_out", screenshot, timerSet = "timer_set"
    // Claude Code
    case claudeStart = "claude_start", claudeApproval = "claude_approval", claudeApproved = "claude_approved"
    case claudeRejected = "claude_rejected", claudeDone = "claude_done"
    // Reminders
    case reminder = "reminder_chime", water = "reminder_water", breakTime = "reminder_break"
    case calendar = "reminder_calendar", reminderDone = "reminder_done"
    // GitHub
    case githubPing = "github_ping", ciFailed = "github_ci_failed", ciPassed = "github_ci_passed"

    enum Family: String, CaseIterable {
        case zera, island, claude, reminders, github
        var title: String {
            switch self {
            case .zera: return "Zera"
            case .island: return "Island"
            case .claude: return "Claude Code"
            case .reminders: return "Reminders"
            case .github: return "GitHub"
            }
        }
        /// GitHub news is background chatter: off until you turn it on.
        var onByDefault: Bool { self != .github }
    }

    var family: Family {
        switch self {
        case .tap, .huff, .hello, .wake, .lift, .land, .caption,
             .fileHover, .fileCatch, .fileReject, .fileDragOut, .screenshot, .timerSet: return .zera
        case .islandOpen, .islandClose, .tab, .button: return .island
        case .claudeStart, .claudeApproval, .claudeApproved, .claudeRejected, .claudeDone: return .claude
        case .reminder, .water, .breakTime, .calendar, .reminderDone: return .reminders
        case .githubPing, .ciFailed, .ciPassed: return .github
        }
    }

    /// Whisper / soft / alert, relative to the volume setting.
    var gain: Float {
        switch self {
        case .caption, .islandOpen, .islandClose, .tab, .button, .fileHover, .fileDragOut, .hello: return 0.55
        case .claudeApproval, .claudeDone, .reminder, .water, .breakTime, .calendar: return 1.0
        default: return 0.8
        }
    }

    /// Taps rotate through three pitches so a run of taps doesn't sound identical.
    var files: [String] { self == .tap ? ["zera_tap_1", "zera_tap_2", "zera_tap_3"] : [rawValue] }
}

/// Plays Zera's sounds: preloaded, one at a time, and only the families you have switched on.
/// Call it from the main thread.
final class SoundService {
    static let shared = SoundService()

    private static let enabledKey = "sounds.enabled"
    private static let volumeKey = "sounds.volume"
    private static func familyKey(_ f: ZeraSound.Family) -> String { "sounds.family.\(f.rawValue)" }

    var enabled: Bool {
        get { UserDefaults.standard.object(forKey: Self.enabledKey) as? Bool ?? true }
        set { UserDefaults.standard.set(newValue, forKey: Self.enabledKey) }
    }
    /// 0…1, on top of the Mac's own volume.
    var volume: Float {
        get { UserDefaults.standard.object(forKey: Self.volumeKey) as? Float ?? 0.7 }
        set { UserDefaults.standard.set(max(0, min(1, newValue)), forKey: Self.volumeKey) }
    }
    func isOn(_ f: ZeraSound.Family) -> Bool {
        UserDefaults.standard.object(forKey: Self.familyKey(f)) as? Bool ?? f.onByDefault
    }
    func set(_ f: ZeraSound.Family, on: Bool) { UserDefaults.standard.set(on, forKey: Self.familyKey(f)) }

    /// Two players per file, so a sound can restart while its last play is still ringing out.
    private var players: [String: [AVAudioPlayer]] = [:]
    private var tapIndex = 0
    private var lastPlayAt: CFTimeInterval = 0
    private var lastPlayed: [ZeraSound: CFTimeInterval] = [:]

    /// Within this window after one sound, the next is skipped: one sound at a time.
    static let minGap: CFTimeInterval = 0.12
    /// The same sound won't repeat faster than this.
    static let minRepeat: CFTimeInterval = 0.4

    private init() {
        guard let dir = Self.locate() else { return }
        for sound in ZeraSound.allCases {
            for name in sound.files {
                let url = dir.appendingPathComponent(name + ".wav")
                let pair = (0..<2).compactMap { _ in try? AVAudioPlayer(contentsOf: url) }
                pair.forEach { $0.prepareToPlay() }
                if !pair.isEmpty { players[name] = pair }
            }
        }
    }

    private static func locate() -> URL? {
        var candidates: [URL] = []
        if let r = Bundle.main.resourceURL { candidates.append(r.appendingPathComponent("Sounds")) }
        // `swift run` from the repository.
        candidates.append(URL(fileURLWithPath: FileManager.default.currentDirectoryPath).appendingPathComponent("Resources/Sounds"))
        var u = (Bundle.main.executableURL ?? URL(fileURLWithPath: CommandLine.arguments[0])).deletingLastPathComponent()
        for _ in 0..<5 {
            candidates.append(u.appendingPathComponent("Resources/Sounds"))
            u = u.deletingLastPathComponent()
        }
        return candidates.first { FileManager.default.fileExists(atPath: $0.appendingPathComponent("caption_pop.wav").path) }
    }

    /// Plays `sound` unless sounds are off for it, or another sound has just started.
    /// Returns whether it played.
    @discardableResult
    func play(_ sound: ZeraSound) -> Bool {
        guard enabled, isOn(sound.family) else { return false }
        let now = CACurrentMediaTime()
        guard now - lastPlayAt >= Self.minGap else { return false }
        if let last = lastPlayed[sound], now - last < Self.minRepeat { return false }
        let name: String
        if sound == .tap { name = sound.files[tapIndex % 3]; tapIndex += 1 } else { name = sound.rawValue }
        guard let pair = players[name], let player = pair.first(where: { !$0.isPlaying }) ?? pair.first else { return false }
        player.volume = volume * sound.gain
        player.currentTime = 0
        player.play()
        lastPlayAt = now
        lastPlayed[sound] = now
        return true
    }

    /// For quiet extras (the caption tick): only when nothing has played for a moment.
    @discardableResult
    func playIfQuiet(_ sound: ZeraSound, quietFor: CFTimeInterval = 0.4) -> Bool {
        guard CACurrentMediaTime() - lastPlayAt >= quietFor else { return false }
        return play(sound)
    }
}
